### ISSUE TITLE
Vivecraft not working with vehicle mod 1.16.4

### ISSUE THREAD

**Issue by cadergator10** [MrCrayfish/Obfuscate#10]
Hello and Happy Thanksgiving! (not sure if you have this holiday, but I do lol) So, I have been trying to get the vehicle mod to work with vivecraft for quite a while. I figured out it was obfuscate causing the problem. There was a thread on here with an optifine incompatability that likely caused the problem (you said optifine patches something your mod does too, which Vivecraft uses in it's mod.) I wanted to make a thread to get any possible support, as you were able to make a video about your vehicle mod before with vr. Is there a way to bypass this?

**Comment by MrCrayfish** [comment]
I just updated the mod with a community PR that makes it compatible with Optifine. It will fix the issue.
