### ISSUE TITLE
Pls Port to 1.16.4!?

### ISSUE THREAD

**Issue by MrScautHD** [MrCrayfish/Obfuscate#11]
Can you pls port to the Newst Mapping Version of 1.16.4? pls

**Comment by MrScautHD** [comment]
@MrCrayfish

**Comment by MrCrayfish** [comment]
1.16.3 version works for 1.16.4

**Comment by MrScautHD** [comment]
@MrCrayfish When i will add the Build Scirpt in my Build.gradle make it Errors(Obfuscate 3043369 not found...)

or is this line not Right?
compile fg.deobf('curse.maven:obfuscate:3043369')

**Comment by MrScautHD** [comment]
> Could not find curse.maven:obfuscate:3043369_mapped_snapshot_20201028-1.16.3.

**Comment by MrScautHD** [comment]
@MrCrayfish ?
