### ISSUE TITLE
Obfuscate Build Error!

### ISSUE THREAD

**Issue by loli252** [MrCrayfish/Obfuscate#13]
I have add the Obfuscate Build Scipt in my Build.gradle and now make it problems!
Could not find curse.maven:obfuscate:3043368_mapped_snapshot_20200514-1.15.1.

Build.gradle

repositories {
    maven {
        url = "https://www.cursemaven.com"
    }
}

dependencies {
    compile fg.deobf('curse.maven:obfuscate:3043368')
}

**Comment by MrScautHD** [comment]
i think the Problem is Curseforge change to Overwolf but no idea how fix this now :/

**Comment by MrCrayfish** [comment]
If that's the case, I can't do much about it for now. I plan to host my own maven at some point so I don't have to rely on CurseForge.

**Comment by MrScautHD** [comment]
@loli252 @MrCrayfish the change to Overwolf have Changed the Projekt id.
With this code is it working:

repositories {
maven {
url = "https://www.cursemaven.com"
}
}

dependencies {
compile fg.deobf("curse.maven:obfuscate-289380:3043368")
}

**Comment by MrCrayfish** [comment]
As @MrScautHD mentioned.
