### ISSUE TITLE
My Minecraft keeps crashing when I play it with Obfuscate.

### ISSUE THREAD

**Issue by MrBunnyRabbit** [MrCrayfish/Obfuscate#14]
So every time I play my Minecraft with the Obfuscate mod, it keeps crashing. I'd like to know why and how I can fix this.

**Comment by Tsoccerguy3** [comment]
not compatible with Optifine if thats installed. You need to provide logs and more info

**Comment by Tsoccerguy3** [comment]
issue is fixed here https://github.com/JacksonPlayz/Obfuscate/tree/mixin . You can compile yourself or wait for MrCrayfish to pull this fix

**Comment by MrCrayfish** [comment]
Fixed in 0.5.1!
