### ISSUE TITLE
Not compatible with Optifine

### ISSUE THREAD

**Issue by MrScautHD** [MrCrayfish/Obfuscate#15]
Hey i have tested Obfuscate with optifine and my game crashed then can you fix this pls?

**Comment by kestrel1110** [comment]
All I know is that because of optifine's graphics settings and animations you can't have weird things, so when forge prepares the two mods it can't handle it and it crashes.

**Comment by MrScautHD** [comment]
@MrCrayfish couldn't MrCrayFish fix that?

**Comment by IchigoGames** [comment]
can 100% confirm that this core mod crash optfine https://pastebin.com/vaaD5C48

**Comment by Tsoccerguy3** [comment]
issue is fixed here https://github.com/JacksonPlayz/Obfuscate/tree/mixin . You can compile yourself or wait for MrCrayfish to pull this fix

**Comment by MrCrayfish** [comment]
Fixed in 0.5.1!
