### ISSUE TITLE
can't load obfucate for MrCrayfish's gun

### ISSUE THREAD

**Issue by IndefiniteCalculus** [MrCrayfish/Obfuscate#24]
![image](https://user-images.githubusercontent.com/55014395/109661570-1231b580-7ba5-11eb-9d44-3a719f027e19.png)
It seems like MrCrayfish's gun has supported 1.16.5 but obfucate hadn't. 
![image](https://user-images.githubusercontent.com/55014395/109662615-3772f380-7ba6-11eb-90cd-3aa742988d4d.png)

**Comment by MrCrayfish** [comment]
You haven't installed Obfuscate
![image](https://user-images.githubusercontent.com/4958241/109755744-79e41100-7c36-11eb-84c5-2ab23f49e1e1.png)

**Comment by IndefiniteCalculus** [comment]
I got it, thanks
