### ISSUE TITLE
Obfuscate 0.6.0 make a mixin error in my workspace

### ISSUE THREAD

**Issue by MrScautHD** [MrCrayfish/Obfuscate#25]
Hey Obfuscate 0.6.0 make a error in my workspace

My Console:
![unknown](https://user-images.githubusercontent.com/65916181/111065228-f689b180-84b8-11eb-95d5-3d95ef750270.png)

**Comment by MrCrayfish** [comment]
Have you added `property 'mixin.env.disableRefMap', 'true'` to your run configurations? If yes, it's most likely that the mappings aren't the same. This is one downside to mixins, they only reference down to searge names and not the other way. To fix this though you just have to match the mappings of Obfuscate in your workspace.
