### ISSUE TITLE
Latest Forge (1.16.5) Version Not Supported Anymore

### ISSUE THREAD

**Issue by K3nni** [MrCrayfish/Obfuscate#30]
3 days ago i encountered an error with obfuscate which said the following,
https://imgur.com/RQ4xmMh
at first i thought, "oh the file i have may have just been corrupted" so i re downloaded both the mods seen in the screenshot provided, still kept showing the same error, then i remembered that i have just downloaded the newest version of forge which was also released 3 days ago, the same day the error started popping up. So i thought to myself "maybe forge is the problem" so i downloaded the previous version of forge and it all worked completely fine, so i am assuming that the latest version of forge clearly does not support this mod anymore, and i hope you may have the time to update your mod thanks.

**Comment by GreabGroovy** [comment]
Yeah i got the same issue, any help?

**Comment by MrCrayfish** [comment]
Boss tools mod is not specifying the dependencies correctly. This will only be an issue if you are using Forge 36.1.10 or higer. Please contact the author of bosstools to update their dependency defintions in their mods.toml file.
