### ISSUE TITLE
Boss Tools Doesn't work

### ISSUE THREAD

**Issue by Beyond1nfinity** [MrCrayfish/Obfuscate#32]
![2021-05-14 22_52_28-](https://user-images.githubusercontent.com/84192277/118288670-36940180-b507-11eb-989d-67b7fe0033bf.png)
when i open 1.16.5 mod boss tools says it needs obfuscate and currently it says "currently, obfuscate is at 0.6.1"

**Comment by MrCrayfish** [comment]
Boss tools needs to update their dependency information.
