### ISSUE TITLE
Obfuscate 0.6.0 mixin error (@shadow?)

### ISSUE THREAD

**Issue by TamashiDev** [MrCrayfish/Obfuscate#45]
Hello i have strange mixin crash when i run client (sorry for using that crappy mod maker :D)

Adding "property 'mixin.env.disableRefMap', 'true'" fixed error with itemstack mixins

But now i'm getting other crash:
![a](https://user-images.githubusercontent.com/71899967/143722803-d8aa790e-0c65-4a0e-b56f-d7e9dd1ae617.png)

**Comment by MrCrayfish** [comment]
You need to specify the remapping file too.
```gradle
property 'mixin.env.remapRefMap', 'true'
property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"
 ```
