### ISSUE TITLE
Incompatible with the Mod "ViveCraft"

### ISSUE THREAD

**Issue by LunarMeal** [MrCrayfish/Obfuscate#65]
I have installed ViveCraft Mod, which is a mod that allows me to play MineCraft with VR. When I installed the module MyClayFish's Gun, I found that the model of the gun was always aimed at me, and the direction in which bullets were fired was not in the direction the gun was aimed, but in the direction my eyes were looking. Please refer to the video demonstration below for details

https://github.com/MrCrayfish/Obfuscate/assets/60291398/9bc50d71-fea8-4fdf-b350-ead29b18c616

**Comment by MrCrayfish** [comment]
The Gun Mod is only designed for the normal version of the game. No plans to support Vivecraft.
