### ISSUE TITLE
Doesn't work on 1.14

### ISSUE THREAD

**Issue by Schnittchen1423** [MrCrayfish/Obfuscate#7]
I tried to get your vehicle mod and needed **Obfuscate** for 1.14.4. Looked at your website. THERE WAS NO 1.14.4 DOWNLOAD BUTTON!!! BUT YOU SAID THAT!!! Okay, sorry but I went crazy. Honestly. so, I'd love to see a 1.14.4 button on your website. Thank you.

**Comment by MrCrayfish** [comment]
Try CurseForge if the download isn't on my website. https://www.curseforge.com/members/mrcrayfish/projects
