### ISSUE TITLE
Cannot find Obfuscate

### ISSUE THREAD

**Issue by Apoptosis847639** [MrCrayfish/Obfuscate#9]
So. I was going to build my mod(to gen all of the natives) And it gives me this:

Could not find curse.maven:obfuscate:<2946425>_mapped_snapshot_20200514-1.15.1.

I do not know why "_mapped_snapshot_20200514-1.15.1." is there.

Can you help me?

**Comment by MrCrayfish** [comment]
Which version of Minecraft are you developing for? It sounds like you haven't included the CurseForge repositories to your build.gradle.

```gradle
repositories {
    maven {
        url = "https://www.cursemaven.com"
    }
}
```

**Comment by Apoptosis847639** [comment]
Maybe. Well. 1.15.2

**Comment by MrScautHD** [comment]
yea i have the same problem but for 1.16 @MrCrayfish

**Comment by MrScautHD** [comment]
@Jaantheman have you found a fix?
